/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CadProdutoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import model.CadProdutoM;

/**
 *
 * @author gabri
 */
public class ProdutoCadV extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoCad
     */
    public ProdutoCadV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tb01 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadName = new javax.swing.JTextField();
        cadPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cadQtd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cadDesc = new javax.swing.JTextField();
        cadSubmitButton = new javax.swing.JButton();
        listProd = new javax.swing.JButton();
        editProd = new javax.swing.JButton();
        editProd1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        Tb01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "E-Mail", "Sexualidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb01MouseClicked(evt);
            }
        });
        Tb01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tb01KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tb01);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadatro de produto");

        jLabel2.setText("Nome");

        cadPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadPriceKeyTyped(evt);
            }
        });

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        cadQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadQtdActionPerformed(evt);
            }
        });
        cadQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadQtdKeyTyped(evt);
            }
        });

        jLabel5.setText("Descrição");

        cadSubmitButton.setBackground(new java.awt.Color(204, 255, 204));
        cadSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadSubmitButton.setText("Registrar");
        cadSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSubmitButtonActionPerformed(evt);
            }
        });

        listProd.setText("Listar produtos");
        listProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProdActionPerformed(evt);
            }
        });

        editProd.setText("Editar produto");
        editProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProdActionPerformed(evt);
            }
        });

        editProd1.setText("Deletear produto");
        editProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProd1ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nome", "Preço", "Quantidade", "Descrição"
            }
        ));
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cadName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadPrice, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(cadQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editProd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listProd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editProd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(listProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(editProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      private void iniciarTabela()
    {
        

                try
                {


                    limparTabela();
                    CadProdutoDao cadastroPDao = new CadProdutoDao();
                    ArrayList<CadProdutoM> listaCadastros;
                    listaCadastros = cadastroPDao.consultar(); //consulta todos os registros da tabela Escola

                    //Resgata o modelo da tabela            
                    DefaultTableModel modeloTabela = (DefaultTableModel) Table.getModel();

                    for(CadProdutoM cadastroP : listaCadastros)
                    {
                        //adiciona em cada linha da tabela da tela o conteúdo de cada posição da listaEscolas
                        modeloTabela.addRow(new String[]{Integer.toString(cadastroP.getId()), 
                                                                          cadastroP.getName(), 
                                                                          cadastroP.getDesc(), 
                                                                          String.valueOf(cadastroP.getPrice()),
                                                                          String.valueOf(cadastroP.getQtd())});
                    }

                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
     
    }
 
      private void atualizaTabela(CadProdutoDao cadastroPDao)
    {
        

                try
                {


                    limparTabela();

                    ArrayList<CadProdutoM> listaCadastros;
                    listaCadastros = cadastroPDao.consultar(); //consulta todos os registros da tabela Escola

                    //Resgata o modelo da tabela            
                    DefaultTableModel modeloTabela = (DefaultTableModel) Table.getModel();

                    for(CadProdutoM cadastroP : listaCadastros)
                    {
                        //adiciona em cada linha da tabela da tela o conteúdo de cada posição da listaEscolas
                        modeloTabela.addRow(new String[]{Integer.toString(cadastroP.getId()), 
                                                                          cadastroP.getName(), 
                                                                          cadastroP.getDesc(), 
                                                                          String.valueOf(cadastroP.getPrice()),
                                                                          String.valueOf(cadastroP.getQtd())});
                    }

                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
     
    }
 
    private void limparCampos()
    {
        cadPrice.setText("");
        cadName.setText("");
        cadDesc.setText("");
        cadQtd.setText("");
    }
    
     private void limparTabela()
    {
        //percorre a tabela e exclui todas as linhas
        while(Table.getRowCount() > 0) 
        {
            DefaultTableModel dm = (DefaultTableModel) Table.getModel();
            dm.getDataVector().removeAllElements();
        }
    }

    
    private void cadSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSubmitButtonActionPerformed
        
         if((cadPrice.getText().trim().isEmpty()) 
               || (cadName.getText().trim().isEmpty()) 
               || (cadDesc.getText().trim().isEmpty())
               || (cadQtd.getText().trim().isEmpty()))
            {
                   JOptionPane.showMessageDialog(null, "Dados Inválidos");
                   cadName.requestFocus();
            }else{
                try
                {    
                    
                    CadProdutoM cadastroP = new CadProdutoM();

                  cadastroP.setName(cadName.getText());
                  cadastroP.setDesc(cadDesc.getText());
                  cadastroP.setQtd(Integer.parseInt(cadQtd.getText()));
                  cadastroP.setPrice(Integer.parseInt(cadPrice.getText()));         
                  CadProdutoDao cadastroPDao = new CadProdutoDao();
                  cadastroPDao.inserir(cadastroP); 
                  limparTabela();
                  atualizaTabela(cadastroPDao);
                  limparCampos(); 
                  
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                } 
            }
             

    }//GEN-LAST:event_cadSubmitButtonActionPerformed

    private void Tb01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb01MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tb01MouseClicked

    private void Tb01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tb01KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_Tb01KeyPressed

    private void listProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProdActionPerformed
        // TODO add your handling code here:
        iniciarTabela();
    }//GEN-LAST:event_listProdActionPerformed

    private void editProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProdActionPerformed
        // TODO add your handling code here:
        
        new ProdutoEdit().setVisible(true);
    }//GEN-LAST:event_editProdActionPerformed

    private void cadQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadQtdActionPerformed

    private void cadPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadPriceKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if(!Character.isDigit((c))){
            evt.consume();
        }
    }//GEN-LAST:event_cadPriceKeyTyped

    private void cadQtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadQtdKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if(!Character.isDigit((c))){
            evt.consume();
        }
    }//GEN-LAST:event_cadQtdKeyTyped

    private void editProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProd1ActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        new ProdutoDelete().setVisible(true);

    }//GEN-LAST:event_editProd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoCadV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTable Tb01;
    private javax.swing.JTextField cadDesc;
    private javax.swing.JTextField cadName;
    private javax.swing.JTextField cadPrice;
    private javax.swing.JTextField cadQtd;
    private javax.swing.JButton cadSubmitButton;
    private javax.swing.JButton editProd;
    private javax.swing.JButton editProd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listProd;
    // End of variables declaration//GEN-END:variables
}
